# Generated by Django 4.2.7 on 2025-06-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Biografía del usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='es', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('auto', 'Automático'), ('light', 'Claro'), ('dark', 'Oscuro')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/Mexico_City', max_length=50),
        ),
    ]
