# Generated by Django 4.2.7 on 2025-06-26 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('session_reminders', models.BooleanField(default=True)),
                ('appointment_confirmations', models.BooleanField(default=True)),
                ('newsletter', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('profile_visibility', models.CharField(choices=[('private', 'Privado'), ('public', 'Público'), ('therapists', 'Solo terapeutas')], default='private', max_length=20)),
                ('data_sharing', models.BooleanField(default=False)),
                ('analytics', models.BooleanField(default=True)),
                ('third_party', models.BooleanField(default=False)),
                ('camera_enabled', models.BooleanField(default=True)),
                ('microphone_enabled', models.BooleanField(default=True)),
                ('speaker_enabled', models.BooleanField(default=True)),
                ('preferred_quality', models.CharField(choices=[('auto', 'Automático'), ('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='auto', max_length=20)),
                ('theme', models.CharField(choices=[('auto', 'Automático'), ('light', 'Claro'), ('dark', 'Oscuro')], default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuario',
            },
        ),
    ]
